FROM node:20-slim

WORKDIR /app

# Copy our test script
COPY test/env-test.js .

# Set URL-related variables first
ARG NEXT_PUBLIC_APP_BASE_URL
ENV NEXT_PUBLIC_APP_BASE_URL=$NEXT_PUBLIC_APP_BASE_URL \
    NEXTAUTH_URL=$NEXT_PUBLIC_APP_BASE_URL

# Run the test
CMD ["node", "env-test.js"] 